site_name: Lenguaje Java
theme:
  name: 'material'

# Personalizaci贸n del sitio
site_description: "Documentaci贸n sobre Java usando MkDocs"
site_author: "Javier"
repo_name: "Mi Repositorio de Java"
repo_url: "https://github.com/Xavidron12/Lenguaje-Java.git"

nav:
  - Inicio: index.md
  - Introducci贸n: introduccion.md
  - Sintaxis: sintaxis.md
  - Programaci贸n Orientada a Objetos: poo.md
  - Ejemplos: ejemplos.md
